#!/bin/sh

cd $(dirname "$0")

INFO=`cat /proc/cpuinfo 2> /dev/null`
case $INFO in
*"0xd05"*)
	./my355.sh
	;;
*"sun8i"*)
	./my282.sh
	;;
*"SStar"*)
	./miyoomini.sh
	;;
*)
	case "$(pwd)" in
	*"miyoo355/app"*)
		./my355.sh
		;;
	*"miyoo285/app"*)
		./my282.sh
		;;
	*"miyoo354/app"|*"miyoo/app"*)
		./miyoomini.sh
		;;
	esac
	;;
esac
