$(PLATFORM):
	# $@
	cp ./workspace/$@/other/351files/351Files ./build/BASE/Tools/$@/Files.pak/
	cp -r ./workspace/$@/other/351files/res ./build/BASE/Tools/$@/Files.pak/
	# update
	cp ./workspace/$@/install/update.sh ./build/SYSTEM/$@/bin/install.sh
	
